### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mrwangyou** [xuemingxxx/ChiFraud#1]
It seems that the categories 8 and 9 in the readme file are incorrect. It appears that 8 is actually Fake SIM, and 9 is Underground Loan.

**Comment by xuemingxxx** [comment]
> It seems that the categories 8 and 9 in the readme file are incorrect. It appears that 8 is actually Fake SIM, and 9 is Underground Loan.

Thank you for highlighting the mistake. I mistakenly swapped categories 8 and 9, but I have now updated the README file to reflect the correct information.

**Comment by mrwangyou** [comment]
Thanks for your reply.
